# Generated by Django 5.2.1 on 2026-06-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_campaignimage_category_campaign_primary_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='herosection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
