# Generated by Django 5.2.1 on 2026-06-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_herosection_options_herosection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorablecertificate',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='honorablecertificate',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='honorablecertificate',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='honorablecertificate',
            name='study_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/studies/'),
        ),
    ]
