# Generated by Django 5.2.1 on 2026-06-03 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_honorablecertificate_project_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorablecertificate',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_certificates', to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='honorablecertificate',
            name='secondary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_certificates', to='dashboard.category'),
        ),
    ]
