# Generated by Django 5.2.1 on 2026-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_honorablecertificate_primary_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('CAMPAIGN', 'Campaign'), ('HONORS', 'Honors')], default='CAMPAIGN', max_length=20),
        ),
    ]
