# Generated by Django 5.2.1 on 2026-06-03 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_category_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_content_info', models.BooleanField(default=True, verbose_name='Content & Info')),
                ('has_campaigns', models.BooleanField(default=True, verbose_name='Campaigns')),
                ('has_honors_program', models.BooleanField(default=True, verbose_name='Honors Program')),
                ('has_system_security', models.BooleanField(default=True, verbose_name='System & Security')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
