# Generated by Django 5.2.1 on 2026-06-03 19:13

from django.db import migrations


def backfill_staff_permissions(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    StaffPermission = apps.get_model('dashboard', 'StaffPermission')
    for user in User.objects.all():
        StaffPermission.objects.get_or_create(user=user)

def rollback_staff_permissions(apps, schema_editor):
    StaffPermission = apps.get_model('dashboard', 'StaffPermission')
    StaffPermission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_staffpermission'),
    ]

    operations = [
        migrations.RunPython(backfill_staff_permissions, rollback_staff_permissions),
    ]
